# Deploy to Firebase Hosting on PR

name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install dependencies (replace with your package manager if necessary)
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # Build the project (adjust this command according to your build setup)
      - name: Build project
        run: npm run build
        working-directory: ./frontend

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_BIONICLE }}
          projectId: the-bionicle
          entryPoint: ./frontend
